export const courseFiles: Record<string, string> = {
  "3rd–4th Grade Math Complete": "/courses/elementary_complete.pdf",
  "Addition & Subtraction Practice": "/courses/addition_subtraction_short.pdf",
  "Multiplication Tables Mastery": "/courses/multiplication_short.pdf",
  "5th–8th Grade Math Complete": "/courses/middle_complete.pdf",
  "Fractions Made Easy": "/courses/fractions_short.pdf",
  "Decimals & Percentages": "/courses/decimals_short.pdf",
  "Algebra I Bootcamp Complete": "/courses/algebra1_complete.pdf",
  "Intro to Algebra": "/courses/intro_algebra_short.pdf",
  "Solving Equations Practice": "/courses/equations_short.pdf",
  "Geometry Complete Course": "/courses/geometry_complete.pdf",
  "Geometry Basics Practice": "/courses/geometry_short.pdf",
  "Statistics & Probability": "/courses/statistics_short.pdf",
  "ACT Math Complete Prep": "/courses/act_complete.pdf",
  "ACT Math Quick Drill": "/courses/act_short.pdf",
  "GED Math Complete Prep": "/courses/ged_complete.pdf",
  "GED Math Essentials": "/courses/ged_short.pdf",
  "College Algebra Bootcamp": "/courses/college_algebra_complete.pdf",
  "College Algebra Quick Start": "/courses/college_algebra_short.pdf",
  "Financial Literacy Math": "/courses/financial_literacy_complete.pdf",
  "Personal Finance Math Basics": "/courses/financial_literacy_short.pdf",
}
